return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.16.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 8,
  height = 25,
  tilewidth = 8,
  tileheight = 8,
  nextobjectid = 27,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      name = "bg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      image = "map1.png",
      properties = {}
    },
    {
      type = "objectgroup",
      name = "collision",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0.272727,
          y = 26.1818,
          width = 8.81818,
          height = 95.7273,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0.0909091,
          y = 4,
          width = 7.81818,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8.09091,
          y = 25.8182,
          width = 12.9091,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 46.2727,
          y = 29,
          width = 9.63636,
          height = 7.81818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 49.0909,
          y = 28,
          width = 6.63636,
          height = 0.909091,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32.1818,
          y = 47.0909,
          width = 11.6364,
          height = 6.63636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 33.2727,
          y = 46.1818,
          width = 9.36364,
          height = 1.09091,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 54.9091,
          y = 4.81818,
          width = 9,
          height = 32.0909,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56.1818,
          y = 36.9091,
          width = 7.90909,
          height = 45.0909,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 44.1818,
          y = 72.0909,
          width = 11.9091,
          height = 9.81818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9.18182,
          y = 71.9091,
          width = 19,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 28.4545,
          y = 72.9091,
          width = 3.63636,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56.9091,
          y = 82,
          width = 6.90909,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56.1818,
          y = 89,
          width = 7.63636,
          height = 12.0909,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 55.1818,
          y = 101,
          width = 8.63636,
          height = 4.09091,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 54.1818,
          y = 105.091,
          width = 9.72727,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 53.3636,
          y = 109.455,
          width = 10.4545,
          height = 12.5455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 49.3636,
          y = 111.364,
          width = 3.81818,
          height = 10.7273,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 30.1818,
          y = 113.455,
          width = 18.9091,
          height = 8.81818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9.27273,
          y = 114.273,
          width = 20.6364,
          height = 7.54545,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9.45455,
          y = 107.727,
          width = 2.45455,
          height = 6.36364,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
