return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.16.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 8,
  height = 25,
  tilewidth = 8,
  tileheight = 8,
  nextobjectid = 108,
  properties = {},
  tilesets = {
    {
      name = "fish-orange",
      firstgid = 1,
      tilewidth = 4,
      tileheight = 2,
      spacing = 0,
      margin = 0,
      image = "fish-orange.png",
      imagewidth = 8,
      imageheight = 2,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 2,
      tiles = {
        {
          id = 0,
          animation = {
            {
              tileid = "0",
              duration = "500"
            },
            {
              tileid = "1",
              duration = "500"
            }
          }
        }
      }
    }
  },
  layers = {
    {
      type = "imagelayer",
      name = "bg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      image = "map1.png",
      properties = {}
    },
    {
      type = "objectgroup",
      name = "collision",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 26,
          width = 9,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 4,
          width = 8,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 26,
          width = 13,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 46,
          y = 29,
          width = 10,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 49,
          y = 28,
          width = 7,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 47,
          width = 12,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 33,
          y = 46,
          width = 10,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 55,
          y = 4,
          width = 9,
          height = 33,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 37,
          width = 8,
          height = 45,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 44,
          y = 72,
          width = 12,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9,
          y = 72,
          width = 19,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 28,
          y = 73,
          width = 4,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 57,
          y = 82,
          width = 7,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 56.1818,
          y = 89,
          width = 7.63636,
          height = 12.0909,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 55.1818,
          y = 101,
          width = 8.63636,
          height = 4.09091,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 54.1818,
          y = 105.091,
          width = 9.72727,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 53.3636,
          y = 109.455,
          width = 10.4545,
          height = 12.5455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 49,
          y = 111,
          width = 4,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 30,
          y = 113,
          width = 19,
          height = 9,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9.27273,
          y = 114.273,
          width = 20.6364,
          height = 7.54545,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9,
          y = 109,
          width = 3.0909,
          height = 4.90882,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 21,
          y = 27,
          width = 1,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 43,
          y = 73,
          width = 1,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 75,
          width = 1,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9,
          y = 81,
          width = 8,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 21,
          y = 81,
          width = 10,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 51,
          y = 37,
          width = 5,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 54,
          y = 38,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 4.44089e-16,
          width = 47,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "algae",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 29,
          name = "",
          type = "small-bottom",
          shape = "rectangle",
          x = 48,
          y = 82,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "small-top",
          shape = "rectangle",
          x = 21,
          y = 70,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "small-bottom",
          shape = "rectangle",
          x = 14,
          y = 34,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "small-top",
          shape = "rectangle",
          x = 52,
          y = 26,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "small-top",
          shape = "rectangle",
          x = 10,
          y = 24,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "medium-top",
          shape = "rectangle",
          x = 48,
          y = 69,
          width = 2,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "medium-bottom",
          shape = "rectangle",
          x = 17,
          y = 81,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "medium-bottom",
          shape = "rectangle",
          x = 48,
          y = 37,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "medium-top",
          shape = "rectangle",
          x = 41,
          y = 110,
          width = 2,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "medium-top",
          shape = "rectangle",
          x = 22,
          y = 111,
          width = 2,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "fish",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 35,
          name = "",
          type = "orange",
          shape = "rectangle",
          x = 37,
          y = 20,
          width = 4,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "orange",
          shape = "rectangle",
          x = 26,
          y = 43,
          width = 4,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "orange",
          shape = "rectangle",
          x = 45,
          y = 93,
          width = 4,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "coin",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 38,
          y = 45,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 53,
          y = 71,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 49,
          y = 27,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 13,
          y = 25,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 15,
          y = 71,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 65,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 37,
          y = 64,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 19,
          y = 57,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 63,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 41,
          y = 99,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 36,
          y = 100,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 92,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 28,
          y = 98,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 28,
          y = 20,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 35,
          y = 22,
          width = 2,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
